config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resources :articles, only: [:index]
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :src, type: String
  field :alt, type: String
  field :title, type: String
  field :article_type, type: String
  field :filter, type: String
  field :feature_article, type: Boolean
  field :feature_img_src, type: String
  field :main_blurb, type: String
  field :blurb, type: String
  field :instructions, type: String
  field :recipe, type: Array
  field :pics, type: Array
  field :home_image, type: String
end

app/models/home_image.rb
class HomeImage
  include Mongoid::Document
  include Mongoid::Timestamps

  field :src, type: String
  field :title, type: String
  field :path, type: String

  def self.s3_path
    "https://s3.amazonaws.com/ff-image-files/images/"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    home_images = HomeImage.all
    home_images_json = home_images.map { |hi| [hi.src, hi.title, hi.path] }
    images = home_images.map { |hi| hi.src }

    articles = Article.all
    article_info_json = {}
    articles.each do |article|
      article_info_json[article.alt.to_s] = {
        src: article.src,
        alt: article.alt,
        title: article.title,
        article_type: article.article_type,
        filter: article.filter,
        feature_article: article.feature_article,
        feature_img_src: article.feature_img_src,
        main_blurb: article.main_blurb,
        blurb: article.blurb,
        instructions: article.instructions,
        recipe: article.recipe,
        pics: article.pics,
        home_image: article.home_image
      }

      images << article.src
      if article.feature_article
        images << article.feature_img_src
      end
      if article.article_type == 'slide_show'
        images << article.pics
      else
        article.pics.each do |p|
          images << p[0]
          images << p[1]
        end
      end
    end

    render :json => {
      home_images: home_images_json,
      info: article_info_json,
      images: images.flatten
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<%= react_router 'MyRoutes' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bkcamp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Leckerli+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic&subset=latin,greek' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700,100' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Dosis:400,300,200' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Lora" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="main-container" class="container" data-url=<%= articles_url %>>
  <%= yield %>
</body>
</html>